# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'webrtc_test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for webrtc_test
  pod 'OneSignal'

  target 'webrtc_test-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'webrtc_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
